site_name: misdocs
theme:
  name: material
  language: es
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.tabs  # ← ¡Esto activa pestañas horizontales!
    - navigation.sections  # opcional: permite secciones colapsables
    - navigation.expand  # expande secciones automáticamente

plugins:
  - awesome-pages
  - git-revision-date-localized
  - search